### ISSUE TITLE
[BUG] Guzzle error on request

### ISSUE THREAD

**Issue by Advil-Robin** [lahaxearnaud/laravel-pushbullet#11]
I'm trying to send notifications via PushBullet to my mobile phone using the lahaxearnaud/laravel-pushbullet plugin. Only one problem, I installed it correctly and I'm still getting this error: `Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, boolean given, called in vendor\guzzlehttp\guzzle\src\Client.php on line 87 and defined`.

This is my code:

```
<?php

namespace RPR\Http\Controllers;

use DB;
use Auth;
use Redirect;
use Session;
use Mail;
use Validator;
use Carbon\Carbon;
use Illuminate\Http\Request;
use PushBullet;
use RPR\User;
use RPR\News;
use RPR\Sponsors;
use RPR\Partners;
use RPR\Events;
use RPR\Http\Controllers\Controller;

class SiteController extends Controller
{

    /**
     * PostContact
     *
     * @return Response
     */
    public function PostContact(Request $request)
    {
        $messages = [
            'name.required' => 'U moet een naam opgeven.',
            'name.min' => 'Uw naam moet minstens :min tekens bevatten.',
            'email.required' => 'U moet een e-mail adres opgeven.',
            'email.min' => 'Uw e-mail adres moet minstens :min tekens bevatten.',
            'email.email' => 'Uw e-mail adres moet geldig zijn.',
            'subject.required' => 'U moet een onderwerp opgeven.',
            'subject.min' => 'Uw onderwerp moet minstens :min tekens bevatten.',
            'message.required' => 'U moet een bericht opgeven.',
            'message.min' => 'Uw bericht moet minstens :min tekens bevatten.'
        ];

        $rules = [
            'name' => 'required|min:3',
            'email' => 'required|min:3|email',
            'subject' => 'required|min:3',
            'message' => 'required|min:3'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            return Redirect::back()->withInput()->withErrors($validator);
        }

        DB::table('contact')->insert([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'subject' => $request->get('subject'),
            'message' => $request->get('message'),
            'ip' => $request->ip(),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        PushBullet::all()->note('Belangrijk', 'Er is een nieuw contact bericht.');

        $request->session()->flash('alert-success', 'Uw bericht is succesvol verzonden!');
        return Redirect::back();
    }

}
```
The main issue is the `PushBullet::all()->note('Belangrijk', 'Er is een nieuw contact bericht.');` wich does the request. After That is fired, I got the issue. Anyone an idea?

Kindest regards,

Robin

**Comment by lahaxearnaud** [comment]
I will take a look tomorrow

**Comment by lahaxearnaud** [comment]
I can't reproduce your issue on a clean 5.2 laravel project with guzzle 5.3 or guzzle 6.2.

Can you give me more informations about the following dependences of your project ?
- laravel
- guzzle
- lahaxearnaud/laravel-pushbullet (this package)


Sincerly,

Arnaud

**Comment by Advil-Robin** [comment]
I just installed your project (via composer require lahaxearnaud/laravel-pushbullet) and tested the code, there are no other plugins except `pragmarx/tracker`, `geoip2/geoip2`, `illuminate/html`.

**Comment by lahaxearnaud** [comment]
Can you upload the composer.lock file ?

**Comment by Advil-Robin** [comment]
[https://www.dropbox.com/s/e3a64kdlm8p4g49/composer.lock?dl=0](https://www.dropbox.com/s/e3a64kdlm8p4g49/composer.lock?dl=0)

**Comment by Advil-Robin** [comment]
I just installed a fresh copy of `Laravel 5.1` and it still returns the same error. :(

**Comment by Advil-Robin** [comment]
I'm still having this error local as in a production environement. Still returning the same issue in laravel 5.1.

Still no solution?

**Comment by Advil-Robin** [comment]
Could you merge the latest versions?

**Comment by lahaxearnaud** [comment]
There is no pull request to merge.

**Comment by Advil-Robin** [comment]
https://github.com/joetannenbaum/phpushbullet/issues/9#issuecomment-226276136

He says there should be?

**Comment by lahaxearnaud** [comment]
Ok I create a new release v1.1.5

**Comment by Advil-Robin** [comment]
Aah, this can be closed, now everything works! Thanks <3
