### ISSUE TITLE
all() returning error

### ISSUE THREAD

**Issue by LasseRafn** [lahaxearnaud/laravel-pushbullet#4]
Okay, amazing package! Thanks. However, whenever I try to use:

```
Pushbullet::all()->note(...);
```

It returns an error: 
```
Client error response [url] https://api.pushbullet.com/v2/pushes [status code] 400 [reason phrase] Bad Request 
```

While if I select a specific device, it works perfectly.

Hope this makes sense.

**Comment by lahaxearnaud** [comment]
Thx =)

Did the error was in your project ?

**Comment by LasseRafn** [comment]
No problem! =D

Yeah, that’s how I noticed - and then I tried returning all devices, it gave me 10 devices. I only have 3, so it seems like their API returns deleted ones too.
